<?php

namespace AppBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    // /**
    //  * Rechercher les Answer JOIN User JOIN Role
    //  */
    // public function findByJoinedToUser($questionId)
    // {
    //     $query = $this->getEntityManager()->createQuery('
    //         SELECT `a`.*, `u`.`username` AS author_username, `u`.`email` AS author_email, `u`.`is_active` AS author_is_active, `u`.`role_id` AS author_role_id, `r`.`name` AS author_role_name
    //         FROM `answer` AS `a`
    //         JOIN `user` AS `u`
    //             ON `u`.`id` = `a`.`author_id`
    //         JOIN `role` AS `r`
    //             ON `u`.`role_id` = `r`.`id`
    //         WHERE `a`.`question_id` = :questionId
    //     ')->setParameter('questionId', $questionId);
    //
    //     return $query->getResult();
    // }
}
